### ISSUE TITLE
Is it a typo?

### ISSUE THREAD

**Issue by sadqiang** [proudmonkey/Apress-Game-Development-Xamarin.Forms-ASPNET#1]
I am sorry if here is not the right place to ask about your book.

Navigate to the 7th page of your book.

> How to create an ASP.NET MVC 5 project.

Is it a typo? Are you really using ASP.NET MVC 5 project template that has been renamed to ASP.NET Core ? I am afraid I am learning an old template.

**Comment by proudmonkey** [comment]
Hi @sadqiang,

Thank you so much for your interest. The book used ASP.NET MVC 5. 

ASP.NET MVC 5 wasn't renamed to ASP.NET Core.  It was ASP.NET 5 that was renamed.

**Comment by sadqiang** [comment]
Please kindly read [this article](https://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx).  Then your book uses technologies that are partially specific to .Net Framework rather than .Net Core.

**Comment by proudmonkey** [comment]
ASP.NET MVC 5 is not ASP.NET 5. They're different. ASP.NET 5 was the old ASP.NET Core. 

And the book doesn't use ASP.NET Core at all.

**Comment by sadqiang** [comment]
Next time please make a clearer description on the title and introduction pages. I thought your book is about cross platform Xamarin.Forms and .Net Core.

> Understanding Game Development with Xamarin.Forms and ASP.
> NET will walk you through how to build a simple data-driven mobile game
> application using the power of Xamarin.Forms and Web API. We will also
> build a real-time leaderboard page using ASP.NET MVC and SignalR.

**Comment by proudmonkey** [comment]
@sadqiang which part of the book and intro isn't clear? and which part of the book says it's using .NET Core? Perhaps, you are confusing things here.
